//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCrudOp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int car_id { get; set; }
        public string model { get; set; }
        public string color { get; set; }
        public Nullable<int> doors_num { get; set; }
        public Nullable<int> year { get; set; }
    }
}
